### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by tomWoike**
new notebook version 6.1.5.

### CODE REVIEW

**Comment by maxpumperla** [comment]
@tomWoike @ukerzel can I suggest using [`pipreqs`](https://github.com/bndr/pipreqs) to generate requirements reliably? `pip freeze` is terrible and this shouldn't be a manual task.

Might require to convert notebooks to code, e.g. with [`nbdev`](https://github.com/fastai/nbdev) with the [`nbdev_build_lib`](https://nbdev.fast.ai/export2html.html#nbdev_build_lib) command.

**Comment by ukerzel** [comment]
Hello,

I really favour  building a minimal requirements.txt that pins the relevant
versions to avoid any conflict between incompatible dependencies.
We should not use pip freeze. TBH I'm not a great fan of any of these tools
to "automagically" build a requirements.txt.

In our case, the repository + myBinder needs to run reliably without
maintenance for years - we do not have the capacity to chase up changes and
verify everything works all the time...

cheers
uli

**Comment by ukerzel** [comment]
Hi @maxpumperla @tomWoike tbh I'm also not a great fan of building the requirements.txt from the imports..
We need to make sure that all notebooks in the repo work on our myBinder Installation and that things cannot change between now and say, a year in the future, because some dependency has changed or someone committed a notebook with some other imports that were then not tested on our server with all other notebooks.
I really think it should be carefully composed and tested.
We do not have a maintenance team and noone looks after the server - it needs to run as reliably as it can without any intervention or monitoring for potentially years....

**Comment by maxpumperla** [comment]
@ukerzel I'm not saying we should enable something like GitHub actions etc. to periodically trigger updates. All I want is to decrease manual work for PRs such like these. Of course things need to be tested, regardless of what you do. But you can't be serious about having a 102 line requirements.txt, which actually has just 10 reqs, while mentioning reliability and maintainability in the same sentence. ;) anyway, just a suggestion.

**Comment by maxpumperla** [comment]
and, yeah, if somebody checks in a new notebook with different, or potentially conflicting, dependencies, nothing's going to safe you.

**Comment by ukerzel** [comment]
Hi @maxpumperla , indeed no, that's not at all what I'm saying.
What I suggest is that we put the 10 or so dependencies in the requirements.txt along with the versions that we require.
If we need to pin versions of packages, they go there. Then upon executing pip install,, the respecitve packages will be pulled in

So for example,, if we require tensorflow (or whatever) in version x.y.z, that will trigger the installation of numpy. We don't need to fix the version of that - unless we also require that numpy is in a fixed version x1.y1.z1 because of other dependencies or if we require a specific functionality, etc.

We should definitely not have a long autogenerated requirerements.txt but only pin those packages and versions we need and have verified that they work with all notebooks in that repo

**Comment by ukerzel** [comment]
> and, yeah, if somebody checks in a new notebook with different, or potentially conflicting, dependencies, nothing's going to safe you.

that is the point - that is not supposed to happen.
There is a very tight circle of people who can commit to a repo. And whoever commits anything needs to test that they don't break any other notebook

**Comment by maxpumperla** [comment]
@ukerzel ok, got it!

about testing, long-term wouldn't we benefit from a bit of automation? I mentioned nbdev, with which you can include tests into your notebooks etc.  I don't like the sound of manually stepping through notebook cells to see if they still operate. But maybe that's overkill, given that presumably notebooks rarely get touched once created (is that correct?).

**Comment by ukerzel** [comment]
> @ukerzel ok, got it!
> 
> about testing, long-term wouldn't we benefit from a bit of automation? I mentioned nbdev, with which you can include tests into your notebooks etc. I don't like the sound of manually stepping through notebook cells to see if they still operate. But maybe that's overkill, given that presumably notebooks rarely get touched once created (is that correct?).

Yes I agree that automation would be nice...
However...
NBDev - as far as I understand - converts stuff to python code? the notebooks are also used in courses where neither Tutor, MV, or students can code. A notebook with an interactive slider that "just runs" is already the utmost limit of what can be done. Introducing another layer of complexity will be very challenging. We should not look from our perspective were we can use notebooks and code but at the wider use at IUBH where there is a fixed set of notebooks and the instructure points students to them and they "play around" with some interaction and noone has any understanding of python, coding, etc.

Then, technially I don't know how to do it - how do you test that, e.g. the animation of a system created inside the notebook in the RL course "looks sensible"? If there's a good way, that would of course be great.

I'm not saying that we cannot improve - not at all, but we also need to keep those in mind who do not know python, programming but still use notebooks created elsewhere to illustrate things.
If you volunteer to setup something, test it with a couple of courses, also outside the Data Science/ AI realm, that's great :)

And indeed - most notebooks will likely be static. We can add some as the course progresses but since they are not even part of the Deputat, there will be only so much time to do any...

**Comment by maxpumperla** [comment]
right, agree with everything.

nbdev is supposedly bidirectional, but I haven't tested its limits. the point would be to only author notebooks (as we're doing right now), and since they're static, generate a testable python lib from them. Of course you need tests in the first place, otherwise there's no point. but having some, this could make for a reasonable safeguard / minimal CI/CD pipeline.

yeah, so I'm not promising anything, but I'd certainly love to dabble with some features for some of my courses. the Python portfolio one or the upcoming RL course might be good.

**Comment by tomWoike** [comment]
@ukerzel @maxpumperla , thanks for your discussion, now I have a better understanding for the IUBH needs.
The usage of an automation tool was in my case caused by the jupyterlab integration as some modules had to be updated. It is easier to read the versions from the ready built server environment.
But from that stage on, we can easily go ahead with a pinned requirements.txt.

**Pull request merged**
